# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc1fc197391ddffa63350e5dcc1e6e1f097392b01d7a1522b5abdd338badddc99a7c7f097f98b6a00870807bc3a23d350ff46a08e27427de826d2bbd66e3383

test:
  secret_key_base: a9e7f070adc9f96f39c82da76537cc7f76b21185585c22dbecf483c47fec35ffcadd3023fe23aaa7e43236fbaf110ee72311b0f22bd41f5a39aeb8e5f527ae7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
